CREATE TABLE `user` (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    userUUID BINARY(16) NOT NULL,
    userName VARCHAR(100) NOT NULL,
    userEmail VARCHAR(100) NOT NULL UNIQUE,
    userCellphoneNumber VARCHAR(15) NOT NULL UNIQUE,
    userPassword VARCHAR(255) NOT NULL,
    userStatus INT NOT NULL,
    userCreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);