FROM php:8.3-apache
RUN apt-get update && apt-get install -y --no-install-recommends \
    gettext \
    libgettextpo-dev \
    && docker-php-ext-install gettext mysqli pdo_mysql \
    && rm -rf /var/lib/apt/lists/*
