FROM php:8.3-apache
RUN apt-get update && apt-get install -y --no-install-recommends \
    gettext \
    libgettextpo-dev \
    && docker-php-ext-install gettext mysqli pdo_mysql \
    && a2enmod rewrite \
    && sed -ri -e 's!AllowOverride None!AllowOverride All!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf \
    && rm -rf /var/lib/apt/lists/* 